name: Build Tako's extended PocketBase image

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "pb_hooks/**"
      - ".github/workflows/tako.yaml"

permissions:
  contents: read
  packages: write

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.platform }}
      cancel-in-progress: false
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runs-on: ubuntu-24.04
          - platform: linux/arm64
            runs-on: ubuntu-24.04-arm
          - platform: linux/arm/v7
            runs-on: ubuntu-24.04-arm
          - platform: linux/ppc64le
            runs-on: ubuntu-24.04
          - platform: linux/s390x
            runs-on: ubuntu-24.04
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Check Out Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up platform pairs
        id: platform
        run: |
          platform=${{ matrix.platform }}
          echo "pair=${platform//\//-}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Generate Docker image metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ghcr.io/takodotid/pocketbase

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: ./
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,"name=ghcr.io/takodotid/pocketbase",push-by-digest=true,name-canonical=true,push=${{ github.event_name == 'push' }}
          target: tako

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: digests-${{ steps.platform.outputs.pair }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

      - name: Get PocketBase version in Dockerfile
        id: pocketbase
        run: |
          export VERSION=$(cat ./Dockerfile | sed -n 's/.*PB_VERSION=\([0-9.]*\).*/\1/p')
          echo "MAJOR=$(echo $VERSION | cut -d . -f1)" >> $GITHUB_OUTPUT
          echo "MINOR=$(echo $VERSION | cut -d . -f2)" >> $GITHUB_OUTPUT
          echo "PATCH=$(echo $VERSION | cut -d . -f3)" >> $GITHUB_OUTPUT

    outputs:
      MAJOR: ${{ steps.pocketbase.outputs.MAJOR }}
      MINOR: ${{ steps.pocketbase.outputs.MINOR }}
      PATCH: ${{ steps.pocketbase.outputs.PATCH }}

  merge:
    runs-on: ubuntu-24.04
    needs: [build]
    steps:
      - name: Download digests
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Get current unix timestamp
        id: timestamp
        uses: release-kit/unix-timestamp@7ca717caac85efbb45f438eccf3326f54f90947f # v1.0.0

      - name: Generate Docker image metadata
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        id: meta
        with:
          images: ghcr.io/takodotid/pocketbase
          tags: |
            ${{ needs.build.outputs.MAJOR }}-tako
            ${{ needs.build.outputs.MAJOR }}.${{ needs.build.outputs.MINOR }}-tako
            ${{ needs.build.outputs.MAJOR }}.${{ needs.build.outputs.MINOR }}.${{ needs.build.outputs.PATCH }}-tako

            ${{ needs.build.outputs.MAJOR }}-tako-${{ steps.timestamp.outputs.timestamp }}
            ${{ needs.build.outputs.MAJOR }}.${{ needs.build.outputs.MINOR }}-tako-${{ steps.timestamp.outputs.timestamp }}
            ${{ needs.build.outputs.MAJOR }}.${{ needs.build.outputs.MINOR }}.${{ needs.build.outputs.PATCH }}-tako-${{ steps.timestamp.outputs.timestamp }}

            type=sha,prefix=,suffix=-tako,format=short
            type=sha,prefix=,suffix=-tako,format=long

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf 'ghcr.io/takodotid/pocketbase@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ghcr.io/takodotid/pocketbase:${{ steps.meta.outputs.version }}
